database:
  path: ./usr/sqlite3.db
system:
  report_path: ./usr/reports
  screenshot_path: ./usr/screenshots
llm:
  screenshot:
    api:
      connector: gemini
      model: gemini-1.5-flash
    description_gen_interval:
      enabled: true
      hours: 2
      minutes: 0
    screenshot_interval:
      hours: 0
      minutes: 5
    prompt: >
      This image was captured on a user's computer. Describe what the user was working on. Do not expose passwords, other people's names, emails, and 
      other private and secure information.
  report:
    api:
      connector: gemini
      model: gemini-1.5-flash
    prompt: >
      You are an AI assistant tasked with generating a daily activity report for a user based on a series of visual descriptions 
      captured from their computer screen throughout the day. Your job is to summarize this data into brief items describing what 
      the user worked on today.