name: Build and release
on:
  workflow_dispatch:

permissions:
  contents: write

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.extract_version.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Tag Name from wails.json
        id: extract_version
        run: |
          TAG_NAME=$(jq -r '.info.productVersion' wails.json)
          echo "Tag name is: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.tag_name }}
          release_name: Release ${{ steps.extract_version.outputs.tag_name }}
          draft: false
          prerelease: false

  build-ubuntu:
    needs: create-release
    uses: ./.github/workflows/build-ubuntu.yml
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}

  build-windows:
    needs: create-release
    uses: ./.github/workflows/build-windows.yml
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}

  build-macos:
    needs: create-release
    uses: ./.github/workflows/build-macos.yml
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}